// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crossprodnum
NumericMatrix crossprodnum(SEXP AA);
RcppExport SEXP _multiblock_crossprodnum(SEXP AASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodnum(AA));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprodnum
NumericMatrix tcrossprodnum(SEXP AA);
RcppExport SEXP _multiblock_tcrossprodnum(SEXP AASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprodnum(AA));
    return rcpp_result_gen;
END_RCPP
}
// crossprodint
NumericMatrix crossprodint(SEXP AA);
RcppExport SEXP _multiblock_crossprodint(SEXP AASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodint(AA));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprodint
NumericMatrix tcrossprodint(SEXP AA);
RcppExport SEXP _multiblock_tcrossprodint(SEXP AASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprodint(AA));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprodnumnum
NumericMatrix tcrossprodnumnum(SEXP AA, SEXP BB);
RcppExport SEXP _multiblock_tcrossprodnumnum(SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    Rcpp::traits::input_parameter< SEXP >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprodnumnum(AA, BB));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprodintint
NumericMatrix tcrossprodintint(SEXP AA, SEXP BB);
RcppExport SEXP _multiblock_tcrossprodintint(SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    Rcpp::traits::input_parameter< SEXP >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprodintint(AA, BB));
    return rcpp_result_gen;
END_RCPP
}
// crossprodnumnum
NumericMatrix crossprodnumnum(SEXP AA, SEXP BB);
RcppExport SEXP _multiblock_crossprodnumnum(SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    Rcpp::traits::input_parameter< SEXP >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodnumnum(AA, BB));
    return rcpp_result_gen;
END_RCPP
}
// crossprodintint
NumericMatrix crossprodintint(SEXP AA, SEXP BB);
RcppExport SEXP _multiblock_crossprodintint(SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    Rcpp::traits::input_parameter< SEXP >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodintint(AA, BB));
    return rcpp_result_gen;
END_RCPP
}
// crossprodIntint
NumericMatrix crossprodIntint(SEXP AA, SEXP BB);
RcppExport SEXP _multiblock_crossprodIntint(SEXP AASEXP, SEXP BBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type AA(AASEXP);
    Rcpp::traits::input_parameter< SEXP >::type BB(BBSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprodIntint(AA, BB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiblock_crossprodnum", (DL_FUNC) &_multiblock_crossprodnum, 1},
    {"_multiblock_tcrossprodnum", (DL_FUNC) &_multiblock_tcrossprodnum, 1},
    {"_multiblock_crossprodint", (DL_FUNC) &_multiblock_crossprodint, 1},
    {"_multiblock_tcrossprodint", (DL_FUNC) &_multiblock_tcrossprodint, 1},
    {"_multiblock_tcrossprodnumnum", (DL_FUNC) &_multiblock_tcrossprodnumnum, 2},
    {"_multiblock_tcrossprodintint", (DL_FUNC) &_multiblock_tcrossprodintint, 2},
    {"_multiblock_crossprodnumnum", (DL_FUNC) &_multiblock_crossprodnumnum, 2},
    {"_multiblock_crossprodintint", (DL_FUNC) &_multiblock_crossprodintint, 2},
    {"_multiblock_crossprodIntint", (DL_FUNC) &_multiblock_crossprodIntint, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiblock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
