# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprodnum <- function(AA) {
    .Call('_multiblock_crossprodnum', PACKAGE = 'multiblock', AA)
}

tcrossprodnum <- function(AA) {
    .Call('_multiblock_tcrossprodnum', PACKAGE = 'multiblock', AA)
}

crossprodint <- function(AA) {
    .Call('_multiblock_crossprodint', PACKAGE = 'multiblock', AA)
}

tcrossprodint <- function(AA) {
    .Call('_multiblock_tcrossprodint', PACKAGE = 'multiblock', AA)
}

tcrossprodnumnum <- function(AA, BB) {
    .Call('_multiblock_tcrossprodnumnum', PACKAGE = 'multiblock', AA, BB)
}

tcrossprodintint <- function(AA, BB) {
    .Call('_multiblock_tcrossprodintint', PACKAGE = 'multiblock', AA, BB)
}

crossprodnumnum <- function(AA, BB) {
    .Call('_multiblock_crossprodnumnum', PACKAGE = 'multiblock', AA, BB)
}

crossprodintint <- function(AA, BB) {
    .Call('_multiblock_crossprodintint', PACKAGE = 'multiblock', AA, BB)
}

crossprodIntint <- function(AA, BB) {
    .Call('_multiblock_crossprodIntint', PACKAGE = 'multiblock', AA, BB)
}

